# Generated by Django 2.0.6 on 2018-07-01 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='item_name',
            field=models.CharField(max_length=200),
        ),
    ]
