# Generated by Django 2.0.6 on 2018-07-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0002_auto_20180701_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='user_date',
            field=models.DateField(),
        ),
    ]
