# Generated by Django 2.0.6 on 2018-07-08 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0003_auto_20180708_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='compare_date',
            field=models.DateField(default=datetime.datetime(2018, 7, 8, 6, 44, 41, 22830, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cal',
            name='user_date',
            field=models.DateField(verbose_name='%d/%m/%Y'),
        ),
    ]
