# Generated by Django 2.0.6 on 2018-07-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0005_auto_20180708_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='user_date',
            field=models.CharField(max_length=12),
        ),
    ]
