# Generated by Django 2.0.6 on 2018-07-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0006_auto_20180708_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='user_date',
            field=models.DateField(null=True),
        ),
    ]
