# Generated by Django 2.0.6 on 2018-07-08 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0007_auto_20180708_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='compare_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
