# Generated by Django 2.0.6 on 2018-07-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_cal', '0009_auto_20180708_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cal',
            name='compare_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cal',
            name='user_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
